seed: 17
device: "cuda:0"
output: "./output"


dataset:
  dataset: "KittiDataset"
  base_dir: /dataset/data_odometry_color
  image_dir: /dataset/data_odometry_color_mask2former
  pose_dir: /dataset/data_odometry_poses
  sequence: "01"
  max_x_length: -1
  max_y_length: -1

  # resized image size
  image_width: 1241
  image_height: 376

  camera_names:
  - "image_2"
  # - "image_3"
  

train:
  vis: False
  debug_from: -1
  detect_anomaly: False
  start_checkpoint: ""

model:
  bev_resolution: 0.05 # meters
  cut_range: 4
  sh_degree: 3
  use_rgb: True
  opt_xy: False
  white_background: False

optimization:
  epochs: 2
  opt_z: True
  position_lr_init: 0.000016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  feature_lr: 0.0005
  opacity_lr: 0.0001
  scaling_lr: 0.0001
  rotation_lr: 0.0001
  rgb_lr: 0.008
  label_lr: 0.1
  exposure_lr: 0.001
  random_background: False

  seg_loss_weight: 0.06
  smooth_loss_weight: 1
  depth_loss_weight: 0
  z_weight: 0

pipeline:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False
